In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [4]:
X = df.drop('species', axis=1)
y = df['species']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

1.0

In [7]:
from sklearn.svm import SVC
svc = SVC(gamma='auto')
svc.fit(X_train, y_train)
svc.score(X_test, y_test)

1.0

In [8]:
from sklearn.model_selection import GridSearchCV
classifier = GridSearchCV((svc), {
    'C': [1, 10, 20, 30],
    'kernel': ['rbf', 'linear']
}, cv=5, return_train_score=False)

In [9]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [10]:
classifier.cv_results_

{'mean_fit_time': array([0.00694442, 0.00515251, 0.00710201, 0.00611892, 0.01445179,
        0.01150537, 0.0077641 , 0.00961618]),
 'std_fit_time': array([0.00349985, 0.00104192, 0.00300466, 0.00164008, 0.00366663,
        0.00462158, 0.00293811, 0.00202014]),
 'mean_score_time': array([0.00545325, 0.00413394, 0.00550132, 0.0044311 , 0.00713177,
        0.01051006, 0.007762  , 0.0083478 ]),
 'std_score_time': array([0.00237189, 0.00113253, 0.00211869, 0.00068607, 0.00269411,
        0.00512931, 0.00356523, 0.00288759]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [11]:
result = pd.DataFrame(classifier.cv_results_)
result.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006944,0.003500,0.005453,0.002372,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.005153,0.001042,0.004134,0.001133,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.007102,0.003005,0.005501,0.002119,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.006119,0.001640,0.004431,0.000686,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.014452,0.003667,0.007132,0.002694,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5

In [12]:
result[['param_C',	'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [13]:
from sklearn.model_selection import RandomizedSearchCV
classifier_r = RandomizedSearchCV((svc), {
    'C': [1, 10, 20, 30],
    'kernel': ['rbf', 'linear']
}, n_iter = 4, cv=5, return_train_score=False)

In [15]:
classifier_r.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [17]:
classifier_r.cv_results_

{'mean_fit_time': array([0.00505867, 0.00546174, 0.00637436, 0.00412998]),
 'std_fit_time': array([0.00163733, 0.00203839, 0.00277039, 0.00072444]),
 'mean_score_time': array([0.00334339, 0.00633588, 0.00446825, 0.00363164]),
 'std_score_time': array([0.00025488, 0.00289315, 0.00172346, 0.00172707]),
 'param_kernel': masked_array(data=['linear', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[30, 10, 30, 20],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 30},
  {'kernel': 'linear', 'C': 10},
  {'kernel': 'rbf', 'C': 30},
  {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([1.        , 1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([0.9       , 0.96666667, 0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.96      , 0.97333333, 0.96      , 0.96666667]),
 'std_test_score': array([0.04898979, 0.03887301, 0.03887301, 0.0421637 ]),
 'rank_test_score': array([3, 1, 3, 2], dtype=int32)}

In [18]:
result = pd.DataFrame(classifier_r.cv_results_)
result.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005059,0.001637,0.003343,0.000255,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.9,0.900000,1.0,0.960000,0.048990,3
1,0.005462,0.002038,0.006336,0.002893,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.9,0.966667,1.0,0.973333,0.038873,1
2,0.006374,0.002770,0.004468,0.001723,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.9,0.933333,1.0,0.960000,0.038873,3
3,0.004130,0.000724,0.003632,0.001727,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.9,0.933333,1.0,0.966667,0.042164,2

In [19]:
result[['param_C',	'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       30       linear         0.960000
1       10       linear         0.973333
2       30          rbf         0.960000
3       20       linear         0.966667